version: '3.7'
services:
 icesat2-lapigdev:
  build: .
  hostname: icesat2-lapigdev
  container_name: icesat2-lapigdev
  privileged: true
  restart: always
  stdin_open: true
  tty: true
  volumes:
   - '../Icesat2:/APP/Icesat2'
   - '/etc/localtime:/etc/localtime'
   - './.env:/APP/.env'
