DB_NAME_ATL8_QL = 'atl8_ql_raw_v5'
COLLECTION_NAME_QL = 'icesat2v5'

COLLECTION_NAME = 'v009_icesat2'
DB_NAME_ATL3 = 'v009_atl3_raw'
DB_NAME_ATL8 = 'v009_atl8_raw'


username = 'username'
password = 'password'
SERVER='127.0.0.1'
CORE=8

DB_PORT=5432
DB_PORT_MONGO=27017
MONGO_HOST='localhost'
DB_HOST='localhost'
DB_USER='user'
DB_PASS='password'
DATABASE='icesat2'